# Web Scraping

In [1]:
import numpy as np
import pandas as pd

from bs4 import BeautifulSoup as bs
import requests

## 🎈 Ejercicio: Arkansas 🎈

Queremos obtener de la página de Wikipedia de "Arkansas", https://es.wikipedia.org/wiki/Arkansas, la tabla que nos indica la composición étnica a aprtir del censo de EEUU de 2020.

- Revisar la página web de Wikipedia y obtener la tabla en un df
- Sobre el df: revisar qué tipo de columnas tenemos y que valores contienen las mismas
- Renombrar las columnas a nombres más descriptivos
- Eliminar columnas que no sean necesarias
- Cambiar a tipo numérico (realizando los cambios necesarios, %) las columnas que contienen números
- **Realizar un análisis exploratorio sobre la tabla**

In [ ]:
url = 'https://es.wikipedia.org/wiki/Arkansas'

In [ ]:
arkansas=pd.read_html(url, match='Composición étnica a partir del censo de Estados Unidos de 2020')
arkansas_raw=arkansas[0]
arkansas_raw

                           Raza y etnia[11]​  Alone  Alone.1  Total  Total.1
0                          Blanco no hispano  68.5%      NaN  73.2%      NaN
1                                     Negros  14.9%      NaN  16.2%      NaN
2                   Hispanios o Latinos[12]​      —      NaN   8.5%      NaN
3                                  Asiáticos   1.7%      NaN   2.2%      NaN
4                                    Nativos   0.7%      NaN   3.4%      NaN
5  Estadounidenses de las islas del Pacífico   0.5%      NaN   0.6%      NaN
6                                       Otro   0.3%      NaN   1.1%      NaN

In [ ]:
arkansas_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Raza y etnia[11]​  7 non-null      object
 1   Alone              7 non-null      object
 2   Alone.1            0 non-null      float64
 3   Total              7 non-null      object
 4   Total.1            0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 412.0+ bytes

In [ ]:
#Eliminamos las columnas Alone.1 y Total.1 porque no me aportan nada.
arkansas_filt=arkansas_raw.drop(['Alone.1','Total.1'], axis=1)
arkansas_filt

                           Raza y etnia[11]​  Alone  Total
0                          Blanco no hispano  68.5%  73.2%
1                                     Negros  14.9%  16.2%
2                   Hispanios o Latinos[12]​      —   8.5%
3                                  Asiáticos   1.7%   2.2%
4                                    Nativos   0.7%   3.4%
5  Estadounidenses de las islas del Pacífico   0.5%   0.6%
6                                       Otro   0.3%   1.1%

In [ ]:
columnas=['Raza y etnia', 'Solo', 'Total']
arkansas_filt.columns=columnas
arkansas_filt

                                Raza y etnia   Solo  Total
0                          Blanco no hispano  68.5%  73.2%
1                                     Negros  14.9%  16.2%
2                   Hispanios o Latinos[12]​      —   8.5%
3                                  Asiáticos   1.7%   2.2%
4                                    Nativos   0.7%   3.4%
5  Estadounidenses de las islas del Pacífico   0.5%   0.6%
6                                       Otro   0.3%   1.1%

In [ ]:
arkansas_filt = arkansas_filt.replace({'%': ''}, regex=True)
arkansas_filt
arkansas_filt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Raza y etnia  7 non-null      object
 1   Solo          7 non-null      object
 2   Total         7 non-null      object
dtypes: object(3)
memory usage: 300.0+ bytes

In [ ]:
columnas=list(arkansas_filt.columns)
columnas_filtradas=columnas[1:]
columnas_filtradas

arkansas_filt[columnas_filtradas] =arkansas_filt[columnas_filtradas].apply(pd.to_numeric, errors='coerce')
arkansas_filt.info()
arkansas_filt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Raza y etnia  7 non-null      object
 1   Solo          6 non-null      float64
 2   Total         7 non-null      float64
dtypes: float64(2), object(1)
memory usage: 300.0+ bytes

                                Raza y etnia  Solo  Total
0                          Blanco no hispano  68.5   73.2
1                                     Negros  14.9   16.2
2                   Hispanios o Latinos[12]​   NaN    8.5
3                                  Asiáticos   1.7    2.2
4                                    Nativos   0.7    3.4
5  Estadounidenses de las islas del Pacífico   0.5    0.6
6                                       Otro   0.3    1.1

## 🎈 Ejercicio pandas 🎈

- Pandas: scrapear la tabla que contiene informacion sobre los álbums más vendidos por año en todo el mundo (https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos) generando un dataframe con la información del año, nombre del álbum, artista y ventas. Ésta ultima columna deberá tener sus valores en numeros enteros en millones.

In [34]:
url='https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos'
albums=pd.read_html(url,match='2002')
df=albums[1]
df.head()

    Año              Álbum   Artista(s)  Ventas (millones)  Ref(s)
0  2001      Hybrid Theory  Linkin Park                9.0  [191]​
1  2002    The Eminem Show       Eminem               13.9  [192]​
2  2003  Come Away with Me  Norah Jones               11.0  [193]​
3  2004        Confessions        Usher               12.0  [194]​
4  2005                X&Y     Coldplay                8.3  [195]​

In [35]:
df_limpio=df.drop('Ref(s)',axis=1)
columnas=['Año','Album', 'Artista', 'Ventas']
df_limpio.columns=columnas
df_limpio.head()

    Año              Album      Artista  Ventas
0  2001      Hybrid Theory  Linkin Park     9.0
1  2002    The Eminem Show       Eminem    13.9
2  2003  Come Away with Me  Norah Jones    11.0
3  2004        Confessions        Usher    12.0
4  2005                X&Y     Coldplay     8.3

In [36]:
def millon(valor):
  return int(valor*1000000)

df_limpio['Ventas'] = df_limpio['Ventas'].apply(millon)
df_limpio.head(10)

    Año                                      Album          Artista    Ventas
0  2001                              Hybrid Theory      Linkin Park   9000000
1  2002                            The Eminem Show           Eminem  13900000
2  2003                          Come Away with Me      Norah Jones  11000000
3  2004                                Confessions            Usher  12000000
4  2005                                        X&Y         Coldplay   8300000
5  2006                        High School Musical  Artistas varios   7000000
6  2007                      High School Musical 2  Artistas varios   6000000
7  2008  Viva la Vida or Death and All His Friends         Coldplay   6800000
8  2009                          I Dreamed a Dream      Susan Boyle   8300000
9  2010                                   Recovery           Eminem   5700000

## 🎈 Ejercicio beautiful soup🎈

- Beautiful Soup: scrapear la tabla de lenguajes de programación más utilizados (https://www.tiobe.com/tiobe-index/) creando un dataframe con una columna llamada "lenguaje" y otra columna llamada "porcentaje_uso" (cogiendo la info de programming language y ratings respectivamente).

In [63]:
#Hacerlo creando un diccionario, en el ratings intentar no coger el %.
# URL de la págin
url = 'https://www.tiobe.com/tiobe-index/'

# Realizar la solicitud GET a la página
response = requests.get(url)
soup = bs(response.text, 'html.parser')
soup
tables = soup.find_all('table', {'class': 'table table-striped table-top20'})
table=tables[0]
# rows almacena todas las filas (<tr>: table rows) de la tabla encontrada (target_table)
rows = table.find_all('tr')
# table_data se inicializa como una lista vacía que almacenará los datos de la tabla en forma de lista de listas
table_data = []

# Iteramos sobre cada fila de la tabla
for row in rows:

  # Dentro de cada fila, se buscan todas las celdas (<td>: table data cells y <th>: table header), almacenándolas en cols
  cols = row.find_all(['td', 'th'])
  # Se utiliza una lista de comprensión para extraer el texto de cada celda, eliminando cualquier espacio en blanco al inicio y al final (strip=True)
  cols = [col.get_text(strip=True) for col in cols]
  # La lista de textos de celdas (cols) se agrega a table_data, construyendo así una lista de listas donde cada sublista representa una fila de la tabla
  table_data.append(cols)

table_data

[['Jun 2025',
  'Jun 2024',
  'Change',
  'Programming Language',
  'Ratings',
  'Change'],
 ['1', '1', '', '', 'Python', '25.87%', '+10.48%'],
 ['2', '2', '', '', 'C++', '10.68%', '+0.65%'],
 ['3', '3', '', '', 'C', '9.47%', '+0.24%'],
 ['4', '4', '', '', 'Java', '8.84%', '+0.44%'],
 ['5', '5', '', '', 'C#', '4.69%', '-1.96%'],
 ['6', '6', '', '', 'JavaScript', '3.21%', '-0.11%'],
 ['7', '7', '', '', 'Go', '2.28%', '+0.35%'],
 ['8', '9', '', '', 'Visual Basic', '2.20%', '+0.54%'],
 ['9', '11', '', '', 'Delphi/Object Pascal', '2.15%', '+0.62%'],
 ['10', '10', '', '', 'Fortran', '1.86%', '+0.33%'],
 ['11', '25', '', '', 'Ada', '1.70%', '+0.91%'],
 ['12', '8', '', '', 'SQL', '1.55%', '-0.21%'],
 ['13', '27', '', '', 'Perl', '1.47%', '+0.77%'],
 ['14', '21', '', '', 'R', '1.39%', '+0.43%'],
 ['15', '15', '', '', 'PHP', '1.25%', '+0.03%'],
 ['16', '16', '', '', 'Scratch', '1.19%', '+0.02%'],
 ['17', '14', '', '', 'MATLAB', '1.13%', '-0.13%'],
 ['18', '17', '', '', 'Rust', '0.97%', '-0.20%'],
 ['19', '13', '', '', 'Assembly language', '0.91%', '-0.35%'],
 ['20', '20', '', '', 'COBOL', '0.89%', '-0.08%']]

In [72]:
columnas = ['Jun 2025',
  'Jun 2024',
  'Change', '',
  'Programming Language',
  'Ratings',
  'Change']
data = table_data[1:]

# Crear el DataFrame
df = pd.DataFrame(data, columns=columnas)
df.head()

  Jun 2025 Jun 2024 Change   Programming Language Ratings   Change
0        1        1                        Python  25.87%  +10.48%
1        2        2                           C++  10.68%   +0.65%
2        3        3                             C   9.47%   +0.24%
3        4        4                          Java   8.84%   +0.44%
4        5        5                            C#   4.69%   -1.96%

In [73]:
df=df.drop(['Jun 2025',
  'Jun 2024',
  'Change', '',
  'Change'], axis=1)
df.head()

  Programming Language Ratings
0               Python  25.87%
1                  C++  10.68%
2                    C   9.47%
3                 Java   8.84%
4                   C#   4.69%

In [75]:
df=df.replace({'%': ''}, regex=True)
df.head()

  Programming Language Ratings
0               Python   25.87
1                  C++   10.68
2                    C    9.47
3                 Java    8.84
4                   C#    4.69